### ISSUE TITLE
Doc: Examples with pitfalls

### ISSUE THREAD

**Issue by Niko-n-DEV** [443eb9/bevy_entitiles#19]
I decided to fully understand how to work with this crate.

As a result, I found a bunch of incomprehensible things that made me doubt the correctness of my own project.

Here in the examples it seems to sign how and what works, but when trying to write it myself, I encountered multiple import errors, etc. As a result, if you go deeper, it turns out that there are many imports already inside libraries that are implemented by features, etc.; Which slows down the investigation. As a result, it is simply unclear how and what and where to use, everything is cursed and everything is needed, but if you integrate it completely into your system, then your own project may fall.

(Because of the features in bevy_entities, more precisely with serialization, which as a result goes into prescribing [features] at home, breaks the project, because in order to use [features] without errors, you need to have the optional parameter in the dependencies, and it does not allow you to use this dependency in the rest of the code, which happened at me with serde)

**Comment by 443eb9** [comment]
First of all, I apologize for the inconvenience caused. Many people have already opened issues due to incomplete documentation, and I am very willing to improve the documentation. However, I am not quite sure how to achieve complete coverage of the documentation. Could you please tell me which functionalities you think are missing so that I can make improvements accordingly?

Furthermore, I don't quite understand the part in parentheses. Why is it that you can't use this dependency in the remaining code after adding the optional parameter? Could you provide some examples to illustrate this?

**Comment by Niko-n-DEV** [comment]
I've sorted out the problem. The solution is quite simple, when I was trying to figure out this library, I ran into unpredictable problems with dependencies and `features`, then I decided to take a look at cargo.toml, and many points became clear.
Solution, in order not to create a lot of problems for a beginner, you need to at least specify which dependencies are used in this or that example in the very same, so as not to run from point to point in an attempt to understand the structure of the project.

Not everyone is advanced and understands it the first time. Some people generally need time to delve into and understand the structure and subtleties of some things.

**Comment by 443eb9** [comment]
Did you read the `README.md` in `examples`? I thought this could solve problems similar to yours.
