### ISSUE TITLE
Panic on too large dimensions on tileset

### ISSUE THREAD

**Issue by myOmikron** [443eb9/bevy_entitiles#7]
Hi there,
I'd try to use your crate as replacement for `bevy_ecs_tilemap`. I've also encountered the same error there, but when activating the `atlas` feature, the problem was gone.

```
2024-01-14T20:37:52.440892Z ERROR log: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (3)' panicked at /home/omikron/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
      note: label = `tilemap_texture_array`
    Dimension Z value 2816 exceeds the limit of 2048

Encountered a panic in system `bevy_entitiles::render::prepare::prepare_tilemaps`!
thread 'main' panicked at /home/omikron/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/pipelined_rendering.rs:145:45:
called `Result::unwrap()` on an `Err` value: RecvError
```

**Comment by 443eb9** [comment]
Well that's because `wgpu` limits the longest length of texture array to 2048. `bevy_entitiles` will divide the whole image into pieces and each of them takes up one z layer of the final texture array ( which is just as the same as what `bevy_ecs_tilemap` does ) and you have more than 2048 atlases.

I will make a `atlas` feature in the next version and this issue will be fixed then.

**Comment by 443eb9** [comment]
Added `atlas` feature in 0.3.0
